
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/lori/Library/Android/sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.3.0 - arm64
...
